### ISSUE TITLE
[patch] add top-level makefile

### ISSUE THREAD

**Issue by alberth** [chuanma/STSLib#1]
I wanted an easier way to build the application, so I added a toplevel makefile and changed the others a bit

**Comment by alberth** [comment]
Apparently, patches are contributed by forking the project instead of attaching a patch in the issue. I have done so in my forked project now. Sorry for the confusion, you can close this issue.
thank you

**Comment by chuanma** [comment]
I'm also new to github. Let's see how it works for a while.
