### ISSUE TITLE
Syntesized supervisor contains deadlock

### ISSUE THREAD

**Issue by ghost** [chuanma/STSLib#2]
Consider the STS model and specifications below. It consists of a car window control. The motor can move up and down, and the system has two sensors. The sensors can be On(Aan) and Off(Uit).

The motor may only start to move up (down) when the maximally down (up) sensor is on. The motor may only stop if the motor is moving down (up) and the maximally down (up) sensor is on.

The generated state-space contains a deadlock location:
Both sensors are On (Aan) and the motor is Stopped. This location is not marked. There are no outgoing transitions.

STS-file:

root = CarWin_Simple
{
CarWin_Simple = AND {Motor, UpSensor, DownSensor}
Motor = OR {Stopped, MovingDown, MovingUp}
UpSensor = OR {Off, On}
DownSensor = OR {Uit, Aan}
}

Motor
{motorStop, motorMoveUp, motorMoveDown}
{upSOn, downSOff, upSOff, downSOn}
{
[Stopped motorMoveDown MovingDown]
[Stopped motorMoveUp MovingUp]
[MovingDown downSOn MovingDown]
[MovingDown motorMoveUp MovingUp]
[MovingDown motorStop Stopped]
[MovingDown upSOff MovingDown]
[MovingUp downSOff MovingUp]
[MovingUp motorMoveDown MovingDown]
[MovingUp motorStop Stopped]
[MovingUp upSOn MovingUp]
}

UpSensor
{}
{upSOn, upSOff}
{
[Off upSOn On]
[On upSOff Off]
}

DownSensor
{}
{downSOff, downSOn}
{
[Uit downSOn Aan]
[Aan downSOff Uit]
}

{Stopped, Off, Aan}
{{Stopped, Off, Uit}}
{}

SPEC file:
{
}
{
({MovingDown, Uit}, motorStop)
({MovingUp, Off}, motorStop)
({Off, Stopped}, motorStop)
({Uit, Stopped}, motorStop)
({Aan}, motorMoveDown)
({On}, motorMoveUp)
({Stopped}, motorStop)
}

**Comment by chuanma** [comment]
I'll look into this on Thursday night.

**Comment by chuanma** [comment]
Note that all events are controllable in your spec file, which is not supported by current software. 

Also mentioned in my thesis (or monograph) Chapter 4.1, this type of spec requires that all events must be uncontrollable. However, disabling controllable events in spec can be handled by some simple tricks.  I'll try to squeeze some time to work on it.

**Comment by chuanma** [comment]
I just created a new branch 'new_type2_spec' to also allow controllable events to be put in the type 2 spec. I'd appreciate that you may try it and report any bug. Thanks!

**Comment by ghost** [comment]
I have tested the new branch. It generates output as expected. Thanks for adding this functionality.

**Comment by chuanma** [comment]
Thanks for the feedback. I'll merge it back to the master branch in a few weeks, when I am sure there are no bugs.

**Comment by dhendriks** [comment]
It appears this issue could now be closed, as the new_type2_spec branch was merged into the master.

**Comment by ghost** [comment]
Closing old issue, which was apparently merged to master.
